version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install pytest
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo "Running unit tests..."
      - pytest test/ -v --tb=short

  build:
    commands:
      - echo "Building SAM application..."
      - sam build
      - sam package --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
    - .aws-sam/**/*